version: "3.8"

services:
  mysql:
    image: mysql:8.0.33
    container_name: wtm-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
    ports:
      - 3306:3306
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
      - ./sql/my.cnf:/etc/mysql/conf.d/my.cnf
